apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitswap-peer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.bitswapPeer.repoURL }}
    targetRevision: {{ .Values.bitswapPeer.targetRevision }}
    path: helm
    helm:
      releaseName: {{ .Values.bitswapPeer.releaseName }}
      valueFiles:
      {{- range .Values.bitswapPeer.valueFileNames }}
      - {{ . }}
      {{- end }}
      values: |
      {{- toYaml .Values.bitswapPeer.values | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.bitswapPeer.namespace }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
